/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      colors: {
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004f54",
        "background": "#020203",
        "primary-fixed": "#7df4ff",
        "on-surface": "#e5e2e3",
        "on-tertiary-fixed": "#0d1c2d",
        "inverse-primary": "#006970",
        "on-primary-fixed": "#002022",
        "tertiary": "#f2f6ff",
        "on-tertiary-container": "#516073",
        "surface-container-high": "#2a2a2b",
        "surface-container-lowest": "#0e0e0f",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#b9cacb",
        "on-primary-container": "#006970",
        "tertiary-fixed": "#d4e4fa",
        "outline": "#849495",
        "on-tertiary": "#233143",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        "surface": "#131314",
        "primary-container": "#00f0ff",
        "secondary": "#ecb2ff",
        "surface-container-highest": "#353436",
        "surface-bright": "#3a393a",
        "primary": "#dbfcff",
        "tertiary-container": "#ccdbf1",
        "surface-dim": "#131314",
        "on-error": "#690005",
        "inverse-on-surface": "#313031",
        "on-background": "#e5e2e3",
        "on-tertiary-fixed-variant": "#39485a",
        "on-primary": "#00363a",
        "secondary-fixed-dim": "#ecb2ff",
        "secondary-fixed": "#f8d8ff",
        "on-secondary": "#520071",
        "surface-container-low": "#1c1b1c",
        "inverse-surface": "#e5e2e3",
        "surface-variant": "#353436",
        "tertiary-fixed-dim": "#b9c8de",
        "surface-container": "#201f20",
        "secondary-container": "#cf5cff",
        "primary-fixed-dim": "#00dbe9",
        "on-secondary-container": "#480063",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#74009f",
        "on-secondary-fixed": "#320047"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        lg: "48px",
        sm: "12px",
        md: "24px",
        xl: "80px",
        "margin-mobile": "16px",
        base: "8px",
        xs: "4px",
        "margin-desktop": "64px"
      },
      animation: {
        "spin-slow": "spin 3s linear infinite",
      }
    },
  },
  plugins: [],
};
